# Copyright 2019 PEACH LAB. All Rights Reserved.
# Author: goat.zhou@foxmail.com

package(default_visibility = ['//visibility:public'])

cc_library(
  name = "compat",
	hdrs = [
      "basic_types.h",
      "compat.h",
			"macros.h",
	],
)
